##
##  This file will be included by other makefiles and provides the
##  pattern rule to generate dependencies.
##
# Pattern rule to generate dependencies
%.d: %.c
	@set -e; rm -f $@; \
		$(DEPCC) -MM $(CPPFLAGS) $< > $@.$$$$; \
		sed 's,\($*\)\.o[ :]*,\1.o $@ : ,g' < $@.$$$$ > $@; \
		rm -f $@.$$$$
